// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgEWbeVIWBfsTxz-_qQSwKryMMSK78CK4',
    appId: '1:1037476469389:web:555bc7f932c9cf7a5fa0c4',
    messagingSenderId: '1037476469389',
    projectId: 'projectstoredatatest-dd486',
    authDomain: 'projectstoredatatest-dd486.firebaseapp.com',
    storageBucket: 'projectstoredatatest-dd486.firebasestorage.app',
    measurementId: 'G-YE3QXFBL9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHERTJ2h_xYwZ42FDHxmwe0-gs_R0Sc00',
    appId: '1:1037476469389:android:519869ea5519368e5fa0c4',
    messagingSenderId: '1037476469389',
    projectId: 'projectstoredatatest-dd486',
    storageBucket: 'projectstoredatatest-dd486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkyU8JMs-MgDtlfz1SI4lW3H6i4vhQWtM',
    appId: '1:1037476469389:ios:52d40cdfa2e8b8205fa0c4',
    messagingSenderId: '1037476469389',
    projectId: 'projectstoredatatest-dd486',
    storageBucket: 'projectstoredatatest-dd486.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
